### PR TITLE
Tagged pdf

### PR DESCRIPTION
**Pull request by BezrukovM**

### CODE REVIEW

**Comment by bdoubrov** [comment]
I think we can survive without this property:

property topLevelElementCount: Integer;

This is the same as K_size, right?

**Comment by BezrukovM** [comment]
Yes, we can use K_size. Property has been removed.

**Comment by bdoubrov** [comment]
One more remark:

links to CosLang are all optional. So, they should be CosLang? .  Would you please correct this as well

**Comment by BezrukovM** [comment]
Fixed CosLang links

**Pull request merged**
